"""Flip Priority is gone; a list it reversed is detected and put back.

The button reversed modlist.txt end to end, which crashes GAMMA on startup.
"""

import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from commander_gui.modlist import flip_priority, looks_flipped, unflip
from commander_gui.settings import CliProfile, CliSettings

#: The shape of a real GAMMA modlist.txt: header, the pinned end-of-list
#: block, then numbered categories counting down to "1- Audio" last.
GAMMA = [
    "# This file was automatically generated by Mod Organizer.",
    "+Anchor",
    "+G.A.M.M.A. End of List_separator",
    "+NewAddon",
    "+224- Newly added addons_separator",
    "+Warfare",
    "+221- Warfare_separator",
    "+Hud",
    "+162- UI_separator",
    "+Visual",
    "+21- Visual_separator",
    "+Radio",
    "+Music",
    "+1- Audio_separator",
]


class DetectionTest(unittest.TestCase):
    def test_correct_order_is_not_flagged(self):
        self.assertFalse(looks_flipped(GAMMA))

    def test_reversed_order_is_flagged_and_restored_exactly(self):
        flipped = flip_priority(GAMMA)
        self.assertTrue(looks_flipped(flipped))
        self.assertEqual(unflip(flipped), GAMMA)

    def test_lists_without_gamma_categories_are_never_flagged(self):
        self.assertFalse(looks_flipped(["+A", "+Foo_separator", "+B", "+Bar_separator"]))
        self.assertFalse(looks_flipped(["+A", "+2- Two_separator", "+B", "+3- Three_separator"]))

    def test_one_category_moved_by_hand_is_not_a_flip(self):
        lines = list(GAMMA)
        # Move "162- UI" below "21- Visual" - one pair out of order.
        ui = lines[7:9]
        del lines[7:9]
        lines[9:9] = ui
        self.assertFalse(looks_flipped(lines))


class LineEndingTest(unittest.TestCase):
    def test_mo2_crlf_file_survives_flip_and_fix_byte_for_byte(self):
        from commander_gui.modlist import read_lines, save_lines

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "modlist.txt"
            original = ("\r\n".join(GAMMA) + "\r\n").encode("utf-8")
            path.write_bytes(original)
            save_lines(path, flip_priority(read_lines(path)))
            save_lines(path, unflip(read_lines(path)))
            self.assertEqual(path.read_bytes(), original)


class _Base(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        from PySide6.QtWidgets import QApplication

        cls.app = QApplication.instance() or QApplication([])

    def _gamma_dir(self, tmp: str, lines: list[str]) -> tuple[Path, Path]:
        gamma = Path(tmp) / "gamma"
        modlist = gamma / "profiles" / "G.A.M.M.A" / "modlist.txt"
        modlist.parent.mkdir(parents=True)
        modlist.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return gamma, modlist


class ModManagerTest(_Base):
    def test_warning_shows_and_the_fix_restores_the_list_with_a_backup(self):
        from PySide6.QtWidgets import QMessageBox, QStatusBar

        from commander_gui.ui import mod_manager_page
        from commander_gui.ui.mod_manager_page import ModManagerPage

        with (
            tempfile.TemporaryDirectory() as tmp,
            patch.dict(os.environ, {"XDG_CONFIG_HOME": tmp}),
            patch.object(mod_manager_page, "mo2_running", return_value=False),
            patch.object(ModManagerPage, "refresh"),
        ):
            gamma, modlist = self._gamma_dir(tmp, flip_priority(GAMMA))

            class FakeWindow:
                settings = CliSettings(
                    profiles=[CliProfile(active=True, profile_name="M", gamma=str(gamma))]
                )
                install_busy = False
                install_operation = None

                def refresh_settings(self):
                    pass

                def update_mod_counter(self):
                    pass

                def statusBar(self):
                    return QStatusBar()

            page = ModManagerPage(FakeWindow())
            page.show()
            page.profile_combo.addItem("G.A.M.M.A")
            page._load_mods()
            self.assertTrue(page.flip_warning.isVisible())
            self.assertFalse(hasattr(page, "flip_priority_button"))

            with patch.object(
                mod_manager_page.QMessageBox, "question",
                return_value=QMessageBox.StandardButton.Yes,
            ):
                page._fix_flipped_order()
            self.assertEqual(modlist.read_text(encoding="utf-8").splitlines(), GAMMA)
            self.assertFalse(page.flip_warning.isVisible())
            self.assertTrue(list(modlist.parent.glob("modlist-*.bak")))
            page.hide()


class PlayPagePromptTest(_Base):
    def _page(self, gamma: Path):
        from commander_gui.ui.play_page import PlayPage

        class FakeWindow:
            settings = CliSettings(
                profiles=[
                    CliProfile(
                        active=True, profile_name="M", gamma=str(gamma), mo2_profile="G.A.M.M.A"
                    )
                ]
            )

        return PlayPage(FakeWindow())

    def _answer(self, label: str):
        """Make the load-order question pick the button called ``label``."""
        from PySide6.QtWidgets import QMessageBox

        def exec_(box):
            for button in box.buttons():
                if button.text() == label:
                    box._picked = button
            return 0

        return (
            patch.object(QMessageBox, "exec", exec_),
            patch.object(QMessageBox, "clickedButton", lambda box: getattr(box, "_picked", None)),
        )

    def test_fix_and_launch_rewrites_a_reversed_list(self):
        with (
            tempfile.TemporaryDirectory() as tmp,
            patch.dict(os.environ, {"XDG_CONFIG_HOME": tmp}),
            patch("commander_gui.ui.play_page.mo2_running", return_value=False),
        ):
            gamma, modlist = self._gamma_dir(tmp, flip_priority(GAMMA))
            page = self._page(gamma)
            exec_patch, clicked_patch = self._answer("Fix and launch")
            with exec_patch, clicked_patch:
                self.assertTrue(page._confirm_load_order())
            self.assertEqual(modlist.read_text(encoding="utf-8").splitlines(), GAMMA)

    def test_cancel_stops_the_launch_and_changes_nothing(self):
        with (
            tempfile.TemporaryDirectory() as tmp,
            patch.dict(os.environ, {"XDG_CONFIG_HOME": tmp}),
        ):
            flipped = flip_priority(GAMMA)
            gamma, modlist = self._gamma_dir(tmp, flipped)
            page = self._page(gamma)
            exec_patch, clicked_patch = self._answer("Cancel")
            with exec_patch, clicked_patch:
                self.assertFalse(page._confirm_load_order())
            self.assertEqual(modlist.read_text(encoding="utf-8").splitlines(), flipped)

    def test_a_correct_list_launches_without_asking(self):
        from PySide6.QtWidgets import QMessageBox

        with (
            tempfile.TemporaryDirectory() as tmp,
            patch.dict(os.environ, {"XDG_CONFIG_HOME": tmp}),
        ):
            gamma, _modlist = self._gamma_dir(tmp, GAMMA)
            page = self._page(gamma)
            with patch.object(QMessageBox, "exec") as ask:
                self.assertTrue(page._confirm_load_order())
            ask.assert_not_called()


if __name__ == "__main__":
    unittest.main()
