"""Deck Mode's Install mod flow, end to end, on a small FOMOD archive."""

import os
import tempfile
import time
import unittest
import zipfile
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from PySide6.QtCore import QObject, Signal
from PySide6.QtWidgets import QApplication

CONFIG = """<config>
  <moduleName>Tiny Mod</moduleName>
  <installSteps order="Explicit">
    <installStep name="Pick">
      <optionalFileGroups order="Explicit">
        <group name="Colour" type="SelectExactlyOne">
          <plugins order="Explicit">
            <plugin name="Red"><files><folder source="red" destination="" /></files>
              <typeDescriptor><type name="Optional"/></typeDescriptor></plugin>
            <plugin name="Blue"><files><folder source="blue" destination="" /></files>
              <typeDescriptor><type name="Optional"/></typeDescriptor></plugin>
          </plugins>
        </group>
      </optionalFileGroups>
    </installStep>
  </installSteps>
</config>
"""


class _FakeWindow(QObject):
    """The slice of DeckWindow the installer uses."""

    busy_changed = Signal(bool)

    def __init__(self):
        super().__init__()
        self.install_busy = False
        self.install_operation = None
        self.overlays = []
        self.messages = []

    def set_install_busy(self, busy, operation=None):
        self.install_busy = busy
        self.install_operation = operation if busy else None

    def show_overlay(self, overlay, *, stacked=False):
        if not stacked:
            while self.overlays:
                self.dismiss_overlay()
        self.overlays.append(overlay)

    def current_overlay(self):
        return self.overlays[-1] if self.overlays else None

    def dismiss_overlay(self, *, refocus=True):
        if self.overlays:
            overlay = self.overlays.pop()
            overlay.closed.emit()

    def notify(self, message, msecs=3000):
        self.messages.append(message)

    def confirm(self, title, message, on_confirm, **_kwargs):
        on_confirm()

    def update_mod_counter(self):
        pass


class _FakeScreen(QObject):
    def __init__(self, window, gamma: Path, modlist: Path):
        super().__init__()
        self.window = window
        self._gamma = gamma
        self._path = modlist
        self._lines = modlist.read_text(encoding="utf-8").splitlines()
        self.revealed = None

    def profile(self):
        return SimpleNamespace(gamma=str(self._gamma))

    def refresh(self):
        self._lines = self._path.read_text(encoding="utf-8").splitlines()

    def reveal_mod(self, name):
        self.revealed = name


class DeckModInstallTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.app = QApplication.instance() or QApplication([])

    def _wait(self, condition, timeout=20.0):
        end = time.monotonic() + timeout
        while time.monotonic() < end:
            self.app.processEvents()
            if condition():
                return
            time.sleep(0.01)
        self.fail("timed out")

    def test_fomod_archive_installs_into_custom_mods(self):
        from Steamdeck.mod_installer import DeckModInstaller

        tmp = Path(tempfile.mkdtemp())
        archive = tmp / "Tiny Mod.zip"
        with zipfile.ZipFile(archive, "w") as zf:
            zf.writestr("Tiny/fomod/ModuleConfig.xml", CONFIG)
            zf.writestr("Tiny/red/gamedata/configs/colour.ltx", "red")
            zf.writestr("Tiny/blue/gamedata/configs/colour.ltx", "blue")
        gamma = tmp / "gamma"
        (gamma / "mods").mkdir(parents=True)
        modlist = gamma / "profiles" / "G.A.M.M.A" / "modlist.txt"
        modlist.parent.mkdir(parents=True)
        modlist.write_text(
            "# This file was automatically generated by Mod Organizer.\n"
            "+PadMod\n-gamepad_separator\n+Anchor\n-G.A.M.M.A. End of List_separator\n",
            encoding="utf-8",
        )
        window = _FakeWindow()
        screen = _FakeScreen(window, gamma, modlist)
        with (
            patch("Steamdeck.mod_installer.mo2_running", return_value=False),
            patch("Steamdeck.modlist_io.mo2_running", return_value=False),
        ):
            installer = DeckModInstaller(screen)
            installer._archive = archive
            installer._confirm_target("Tiny Mod")
            self.assertTrue(window.install_busy)
            # Extraction finishes, the FOMOD installer replaces the progress.
            self._wait(
                lambda: window.overlays
                and window.overlays[-1].buttons
                and window.overlays[-1].buttons[0].text() == "Install"
            )
            panel = window.overlays[-1].findChildren(QObject)
            from Steamdeck.fomod_panel import DeckFomodPanel

            fomod = next(child for child in panel if isinstance(child, DeckFomodPanel))
            fomod.rows[1].activated.emit()  # Blue
            window.overlays[-1].buttons[0].click()
            self._wait(lambda: not window.install_busy and screen.revealed)

        installed = gamma / "mods" / "Tiny Mod"
        self.assertEqual(
            (installed / "gamedata" / "configs" / "colour.ltx").read_text(encoding="utf-8"),
            "blue",
        )
        self.assertTrue((installed / "meta.ini").is_file())
        lines = modlist.read_text(encoding="utf-8").splitlines()
        # Header kept, then the new mod at the very bottom (file start).
        self.assertEqual(lines[1:3], ["-Tiny Mod", "-Custom Mods_separator"])
        self.assertEqual(screen.revealed, "Tiny Mod")
        self.assertIsNone(installer._staging_root)

    def test_finishing_leaves_a_panel_the_user_opened_meanwhile(self):
        """B hides the progress panel while the install carries on; the
        end of the install must not close whatever is open by then."""
        from PySide6.QtWidgets import QLabel

        from Steamdeck.mod_installer import DeckModInstaller
        from Steamdeck.widgets import DeckOverlay

        tmp = Path(tempfile.mkdtemp())
        archive = tmp / "Plain.zip"
        with zipfile.ZipFile(archive, "w") as zf:
            zf.writestr("gamedata/configs/a.ltx", "x")
        gamma = tmp / "gamma"
        (gamma / "mods").mkdir(parents=True)
        modlist = gamma / "modlist.txt"
        modlist.write_text("+A\n-Foo_separator\n", encoding="utf-8")
        window = _FakeWindow()
        screen = _FakeScreen(window, gamma, modlist)
        with (
            patch("Steamdeck.mod_installer.mo2_running", return_value=False),
            patch("Steamdeck.modlist_io.mo2_running", return_value=False),
        ):
            installer = DeckModInstaller(screen)
            installer._archive = archive
            installer._confirm_target("Plain")
            window.dismiss_overlay()  # B on the progress panel
            other = DeckOverlay("Other", QLabel("x"))
            window.show_overlay(other)
            self._wait(lambda: not window.install_busy and screen.revealed)
        self.assertIs(window.current_overlay(), other)
        self.assertTrue((gamma / "mods" / "Plain" / "gamedata").is_dir())

    def test_cancelling_the_fomod_releases_the_install_lock(self):
        from Steamdeck.mod_installer import DeckModInstaller

        tmp = Path(tempfile.mkdtemp())
        archive = tmp / "Tiny.zip"
        with zipfile.ZipFile(archive, "w") as zf:
            zf.writestr("fomod/ModuleConfig.xml", CONFIG)
            zf.writestr("red/gamedata/a.ltx", "red")
            zf.writestr("blue/gamedata/a.ltx", "blue")
        gamma = tmp / "gamma"
        (gamma / "mods").mkdir(parents=True)
        modlist = gamma / "modlist.txt"
        modlist.write_text("+A\n-Foo_separator\n", encoding="utf-8")
        window = _FakeWindow()
        screen = _FakeScreen(window, gamma, modlist)
        with patch("Steamdeck.mod_installer.mo2_running", return_value=False):
            installer = DeckModInstaller(screen)
            installer._archive = archive
            installer._confirm_target("Tiny")
            self._wait(
                lambda: window.overlays
                and window.overlays[-1].buttons
                and window.overlays[-1].buttons[-1].text() == "Cancel"
                and len(window.overlays[-1].buttons) == 3
            )
            window.dismiss_overlay()  # B
        self.assertFalse(window.install_busy)
        self.assertFalse((gamma / "mods" / "Tiny").exists())
        self.assertEqual(modlist.read_text(encoding="utf-8"), "+A\n-Foo_separator\n")
        self.assertTrue(any("cancelled" in m for m in window.messages))



class DeckArchivePickerHiddenTest(unittest.TestCase):
    """Dot-folders stay out of the browser until "Show hidden folders" is on."""

    @classmethod
    def setUpClass(cls):
        cls.app = QApplication.instance() or QApplication([])

    def _labels(self, picker):
        return [picker.picker.list.item(i).text() for i in range(picker.picker.list.count())]

    def test_hidden_entries_hidden_by_default_and_shown_when_toggled(self):
        from Steamdeck.mod_installer import DeckArchivePicker

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / ".wine").mkdir()
            (root / "Mods").mkdir()
            (root / ".secret.zip").write_bytes(b"")
            (root / "mod.zip").write_bytes(b"")
            picker = DeckArchivePicker(root, lambda _path: None)

            self.assertFalse(picker.hidden_toggle.is_checked())
            text = " ".join(self._labels(picker))
            self.assertIn("Mods", text)
            self.assertIn("mod.zip", text)
            self.assertNotIn(".wine", text)
            self.assertNotIn(".secret.zip", text)

            picker.hidden_toggle.set_checked(not picker.hidden_toggle.is_checked(), notify=True)
            text = " ".join(self._labels(picker))
            self.assertTrue(picker.hidden_toggle.is_checked())
            self.assertIn(".wine", text)
            self.assertIn(".secret.zip", text)

            picker.hidden_toggle.set_checked(not picker.hidden_toggle.is_checked(), notify=True)
            self.assertNotIn(".wine", " ".join(self._labels(picker)))


    def test_opening_a_folder_starts_at_the_top(self):
        from Steamdeck.mod_installer import DeckArchivePicker

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            for i in range(40):
                (root / f"folder{i:02}").mkdir()
                (root / f"folder{i:02}" / "sub").mkdir()
            picker = DeckArchivePicker(root, lambda _path: None)
            picker.resize(800, 400)
            picker.show()
            self.app.processEvents()
            view = picker.picker.list
            view.setCurrentRow(35)
            view.verticalScrollBar().setValue(view.verticalScrollBar().maximum())

            picker.open(root / "folder35")
            self.app.processEvents()
            self.assertEqual(view.currentRow(), 0)
            self.assertEqual(view.verticalScrollBar().value(), 0)

            picker.go_up()
            view.verticalScrollBar().setValue(view.verticalScrollBar().maximum())
            picker.jump_to_top()
            self.app.processEvents()
            self.assertEqual(view.currentRow(), 0)
            self.assertEqual(view.verticalScrollBar().value(), 0)
            picker.hide()


if __name__ == "__main__":
    unittest.main()
